import {useState,useEffect,useRef} from 'react';
import {SettingsPanel} from './SettingsPanel.jsx';
import {ModelSettings,modelReadiness} from './ModelSettings.jsx';
import {PreviewPanel} from './PreviewPanel.jsx';
import Markdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {Plus,X,List,House,FolderSimple,ChatCircleDots,Sparkle,ArrowUp,ArrowRight,Browser,GearSix,SquaresFour,Check,FileText,CalendarBlank,MagnifyingGlass,DotsThree,Archive,ArrowCounterClockwise,CaretRight} from '@phosphor-icons/react';
import {harness,threadFromHistory,titleFromSummary,effectivePlanMode,tokenTelemetry} from './harnessClient.js';
import {local,watch,statusLabels} from './tulipClient.js';
import './workbench.css';
import './tulip.css';
import './markdown.css';

const empty={projects:[],tasks:[],runs:[],todos:[],schedules:[],notifications:[],plans:[],artifacts:[],drafts:[],discussions:[],workItems:[],previews:[],pending:[]};
const activeStatus=['queued','running','waiting','stopping','settling','scheduled','preparing'];
function userText(text='') {return text.replace(/^(\/plan )?\[Tulip 当前工作上下文[\s\S]*?\[\/Tulip\]\s*/,'$1');}
function tokenLabel(value=0) {return value>=1000?`${(value/1000).toFixed(value>=10000?0:1)}k`:String(value);}

function Question({frame,onAnswer}) {
  const [answers,setAnswers]=useState({}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const p=frame.payload;
  async function submit(event) {
    event.preventDefault();setBusy(true);setError('');
    try {
      const list=p.questions.map(q=>({id:q.id,selected:answers[q.id]?.selected||[],...(answers[q.id]?.custom?{custom:answers[q.id].custom}:{})}));
      if(list.some(a=>!a.selected.length&&!a.custom?.trim()))throw Error('请回答每个问题');
      await onAnswer(frame.rpcId,{sessionId:p.sessionId,answer:{answers:list}});
    }catch(e){setError(e.message);}finally{setBusy(false);}
  }
  if(p.type==='approval/requested')return <section className="tu-question"><strong>执行需要确认</strong><p>{p.toolName} · {p.reason}</p><button onClick={()=>onAnswer(frame.rpcId,{sessionId:p.sessionId,approvalId:p.approvalId,outcome:'allowed-once'}).catch(e=>setError(e.message))}>允许本次</button><button onClick={()=>onAnswer(frame.rpcId,{sessionId:p.sessionId,approvalId:p.approvalId,outcome:'rejected'}).catch(e=>setError(e.message))}>拒绝</button><p role="alert">{error}</p></section>;
  const review=p.questions?.length===1&&p.questions[0]?.intent?.kind==='plan-review'?p.questions[0]:null;
  if(review) {
    const approve=review.intent.approve,revise=review.options?.find(option=>option.label!==approve)?.label;
    const decide=async label=>{setBusy(true);setError('');try{await onAnswer(frame.rpcId,{sessionId:p.sessionId,answer:{answers:[{id:review.id,selected:[label],...(answers[review.id]?.custom?.trim()?{custom:answers[review.id].custom.trim()}: {})}]}});}catch(e){setError(e.message);}finally{setBusy(false);}};
    return <section className="tu-plan-review"><header><span><small>规划完成</small><strong>{review.question||'请审阅这份方案'}</strong></span><em>尚未执行</em></header><div className="tu-markdown"><Markdown remarkPlugins={[remarkGfm]}>{review.detail||''}</Markdown></div><label>需要调整的地方（可选）<textarea value={answers[review.id]?.custom||''} onChange={e=>setAnswers({[review.id]:{custom:e.target.value}})} placeholder="补充约束，或说明希望怎么修改…"/></label>{error&&<p role="alert">{error}</p>}<footer>{revise&&<button disabled={busy} onClick={()=>decide(revise)}>继续修改</button>}<button className="primary" disabled={busy} onClick={()=>decide(approve)}>{busy?'提交中…':'确认方案，开始执行'}</button></footer></section>;
  }
  return <form className="tu-question" onSubmit={submit}>{p.questions.map(q=><fieldset key={q.id}><legend>{q.header||'需要你的选择'} · {q.question}</legend>{q.detail&&<pre>{q.detail}</pre>}{q.options?.map(option=><label className="tu-option" key={option.label}><input type={q.multiSelect?'checkbox':'radio'} name={frame.rpcId+q.id} checked={(answers[q.id]?.selected||[]).includes(option.label)} onChange={event=>setAnswers(previous=>({...previous,[q.id]:{...previous[q.id],selected:q.multiSelect?(event.target.checked?[...(previous[q.id]?.selected||[]),option.label]:(previous[q.id]?.selected||[]).filter(x=>x!==option.label)):[option.label]}}))}/><span>{option.label}{option.description&&<small>{option.description}</small>}</span></label>)}<input aria-label={`${q.header||q.question} 补充回答`} placeholder="也可以自己补充…" value={answers[q.id]?.custom||''} onChange={e=>setAnswers(a=>({...a,[q.id]:{...a[q.id],custom:e.target.value}}))}/></fieldset>)}{error&&<p role="alert">{error}</p>}<button type="submit" disabled={busy}>{busy?'提交中…':'确认选择，继续'}</button></form>;
}
function Modal({title,onClose,children,className=''}) {return <div className="wb-overlay" onMouseDown={onClose}><section className={`wb-dialog tu-dialog ${className}`} role="dialog" aria-modal="true" aria-label={title} onMouseDown={e=>e.stopPropagation()}><header><h2>{title}</h2><button aria-label="关闭" onClick={onClose}><X size={18}/></button></header>{children}</section></div>;}

function SidebarTask({summary,task,state,sessions,current,onSelect,taskMenu,setTaskMenu,onArchive}) {
  const children=state.tasks.filter(child=>child.parentTaskId===task?.id&&!child.archivedAt),[open,setOpen]=useState(false);
  useEffect(()=>{if(current===summary.sessionId||children.some(child=>child.sessionId===current))setOpen(true);},[current,summary.sessionId,children.length]);
  const childRunning=children.some(child=>activeStatus.includes(state.runs.find(run=>run.taskId===child.id)?.status));
  return <div className={`wb-task-group ${open?'is-open':''}`}><div className={`wb-task-row ${current===summary.sessionId?'is-current':''}`}><button className="wb-nav-item wb-task" onClick={()=>onSelect(summary)}><ChatCircleDots size={15}/><span>{titleFromSummary(summary)}</span>{(summary.running||childRunning)&&<i className="tu-live"/>}</button>{children.length>0&&<button className="wb-task-expand" aria-label={open?'收起执行会话':'展开执行会话'} onClick={()=>setOpen(value=>!value)}><CaretRight size={13}/><small>{children.length}</small></button>}<button className="wb-task-more" aria-label={`更多：${titleFromSummary(summary)}`} aria-expanded={taskMenu===summary.sessionId} onClick={()=>setTaskMenu(taskMenu===summary.sessionId?null:summary.sessionId)}><DotsThree size={18} weight="bold"/></button>{taskMenu===summary.sessionId&&<div className="wb-task-menu" role="menu"><button role="menuitem" disabled={summary.running||childRunning} onClick={()=>onArchive(summary.sessionId,true)}><Archive size={15}/>归档</button>{(summary.running||childRunning)&&<small>执行中，停止后可归档</small>}</div>}</div>{open&&children.length>0&&<div className="wb-child-tasks">{children.map(child=>{const childSession=sessions.find(item=>item.sessionId===child.sessionId)||{sessionId:child.sessionId,title:child.title};const run=state.runs.find(item=>item.taskId===child.id);return <button className={current===child.sessionId?'is-current':''} key={child.id} onClick={()=>onSelect(childSession)}><span className={`tu-work-dot ${run?.status||'queued'}`}/><span>{child.title}<small>{statusLabels[run?.status]||run?.status||'等待执行'}</small></span></button>;})}</div>}</div>;
}

function ExecutionGroup({task,state,sessions,onSelect}) {
  if(!task)return null;const items=state.workItems.filter(item=>item.parentTaskId===task.id).sort((a,b)=>a.order-b.order);if(!items.length)return null;
  const done=items.filter(item=>item.status==='completed').length;
  return <section className="tu-execution"><header><span><strong>执行会话</strong><small>{done}/{items.length} 已完成 · 独立会话按依赖推进</small></span><em>{items.some(item=>['failed','stopped','interrupted','blocked'].includes(item.status))?'需要处理':done===items.length?'已完成':'执行中'}</em></header><div className="tu-execution-progress"><i style={{width:`${done/items.length*100}%`}}/></div><div className="tu-execution-list">{items.map(item=>{const child=state.tasks.find(row=>row.workItemId===item.id),summary=sessions.find(row=>row.sessionId===child?.sessionId)||child&&{sessionId:child.sessionId,title:child.title};return <button key={item.id} disabled={!summary} onClick={()=>summary&&onSelect(summary)}><span className={`tu-work-dot ${item.status}`}/><span><strong>{item.title}</strong><small>{statusLabels[item.status]||item.status} · {item.mode==='read'?'只读检查':'项目修改'}{item.previewExpected?' · 预期预览':''}</small></span><ArrowRight size={14}/></button>;})}</div></section>;
}

export function Workbench() {
  const [state,setState]=useState(empty),[connected,setConnected]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState('');
  const [sessions,setSessions]=useState([]),[session,setSession]=useState(null),[projectId,setProjectId]=useState(null);
  const [thread,setThread]=useState([]),[prompt,setPrompt]=useState(''),[view,setView]=useState('today'),[sidebar,setSidebar]=useState(true);
  const [projections,setProjections]=useState({});
  const [panel,setPanel]=useState(null),[modal,setModal]=useState(null),[search,setSearch]=useState(''),[taskMenu,setTaskMenu]=useState(null);
  const [skills,setSkills]=useState([]),[children,setChildren]=useState([]),[childText,setChildText]=useState('');
  const [memory,setMemory]=useState(null),[memoryName,setMemoryName]=useState('MEMORY.md'),[memoryNames,setMemoryNames]=useState([]);
  const [selectedPreview,setSelectedPreview]=useState(''),[previewWidth,setPreviewWidth]=useState(()=>Number(localStorage.getItem('tulip-preview-width')||430)),[host,setHost]=useState(null),[models,setModels]=useState([]),[model,setModel]=useState(''),[modelReady,setModelReady]=useState(null);
  const [draftContent,setDraftContent]=useState(''),[selectedDraft,setSelectedDraft]=useState(null),[pendingSend,setPendingSend]=useState(false);
  const [todoInput,setTodoInput]=useState(''),[planText,setPlanText]=useState(''),[planStatus,setPlanStatus]=useState('proposed');
  const [schedule,setSchedule]=useState({title:'',prompt:'',kind:'reminder',at:'',recurrence:'once'}),[artifact,setArtifact]=useState(null);
  const currentRef=useRef(null),currentTaskRef=useRef(null),drafts=useRef({}),follow=useRef(true),threadEl=useRef(null),mounted=useRef(true);
  const project=state.projects.find(p=>p.id===projectId),task=state.tasks.find(t=>t.sessionId===session?.sessionId);
  const run=state.runs.find(r=>r.sessionId===session?.sessionId),running=!!run&&activeStatus.includes(run.status);
  const planMode=effectivePlanMode(projections),telemetry=tokenTelemetry(projections);
  const discussion=state.discussions.find(d=>d.id===run?.discussionId)||state.discussions.find(d=>d.sessionId===session?.sessionId);
  const pending=state.pending.filter(f=>f.payload.sessionId===session?.sessionId||children.some(c=>c.id===f.payload.sessionId));
  const archivedTasks=state.tasks.filter(t=>t.archivedAt);
  const archivedIds=new Set(archivedTasks.map(t=>t.sessionId));
  const recentSessions=sessions.filter(s=>!archivedIds.has(s.sessionId)&&!state.tasks.find(t=>t.sessionId===s.sessionId)?.parentTaskId);
  const notify=message=>setToast(message);
  const act=async(fn)=>{try{return await fn();}catch(e){notify(e.message);return null;}};
  function requireModel() {if(modelReady!==false)return false;setModal('modelSetup');notify('先连接 DeepSeek 或其他模型，密钥只保存在 Harness');return true;}
  async function refresh() {
    const data=await local('state');if(!mounted.current)return;setState(data);setConnected(data.connected);setError('');
    const listed=await harness.listSessions();if(mounted.current)setSessions(listed.items.filter(s=>!s.parentSessionId));
  }
  async function history(id) {const h=await harness.history(id,150);if(currentRef.current===id){setThread(threadFromHistory(h.events));setProjections(h.projections?.values||{});}}
  useEffect(()=>{
    mounted.current=true;let legacy=[];try{legacy=JSON.parse(localStorage.getItem('tulip-os.today-tasks.v1')||'[]');}catch{}
    local('todos/migrate',{items:legacy}).then(refresh).catch(e=>setError(e.message));
    harness.describe().then(h=>{setHost(h);setModel(`${h.provider}::${h.model}`);}).catch(e=>setError(e.message));
    modelReadiness().then(snapshot=>{setModelReady(snapshot.ready);if(!snapshot.ready)setModal('modelSetup');}).catch(()=>setModelReady(false));
    const stop=watch(event=>{if(event.type==='notification')setToast(`${event.notification.title}：${event.notification.text}`);if(event.type==='preview'){setState(s=>({...s,previews:[event.preview,...s.previews.filter(item=>item.id!==event.preview.id)]}));if(event.preview.sessionId===currentRef.current||event.preview.parentTaskId===currentTaskRef.current){setSelectedPreview(event.preview.id);setPanel('preview');}}},data=>{setConnected(data.connected);if(data.pending)setState(s=>({...s,pending:data.pending}));});
    const timer=setInterval(()=>refresh().catch(e=>setError(e.message)),2000);
    return()=>{mounted.current=false;stop();clearInterval(timer);};
  },[]);
  useEffect(()=>{
    currentRef.current=session?.sessionId||null;currentTaskRef.current=task?.id||null;setThread([]);setProjections({});setChildren([]);setChildText('');follow.current=true;
    if(!session?.sessionId)return;const id=session.sessionId;let live=true;
    const load=()=>history(id).catch(e=>{if(live)setError(e.message);});load();
    harness.models(id).then(m=>{if(!live)return;setModel(`${m.current.provider}::${m.current.model}`);setModels(m.groups.flatMap(g=>g.models.map(x=>({...x,provider:g.id,key:`${g.id}::${x.id}`}))));}).catch(e=>{notify(e.message);setModal('modelSetup');});
    const timer=setInterval(()=>{load();harness.children(id).then(data=>{if(live)setChildren(data.entries);}).catch(()=>{});},1500);
    return()=>{live=false;clearInterval(timer);};
  },[session?.sessionId,task?.id]);
  useEffect(()=>{if(follow.current)threadEl.current?.scrollTo({top:threadEl.current.scrollHeight});},[thread,pending.length]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),5500);return()=>clearTimeout(t);},[toast]);
  useEffect(()=>{localStorage.setItem('tulip-preview-width',String(previewWidth));},[previewWidth]);
  useEffect(()=>{const key=e=>{if(e.key==='Escape'){setModal(null);setPanel(null);setTaskMenu(null);}if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setModal('search');}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
  async function select(s) {
    drafts.current[session?.sessionId||'new']=prompt;setPrompt(drafts.current[s.sessionId]||'');setSession(s);setView('task');setModal(null);
    const t=state.tasks.find(t=>t.sessionId===s.sessionId);const p=state.projects.find(p=>p.id===t?.projectId||p.path===s.cwd);setProjectId(p?.id||null);
    const preview=state.previews.find(item=>item.sessionId===s.sessionId||item.parentTaskId===t?.id);if(preview){setSelectedPreview(preview.id);setPanel('preview');}
  }
  function fresh() {drafts.current[session?.sessionId||'new']=prompt;setSession(null);setThread([]);setPrompt('');setView('task');setModal(null);}
  async function create(kind='work',title='新任务') {const t=await local('tasks',{projectId,kind,title});await refresh();setSession({sessionId:t.sessionId,title:t.title});setView('task');return t;}
  async function send(text=prompt) {
    if(typeof text!=='string'||!text.trim()||pendingSend||requireModel())return;setPendingSend(true);
    try {const t=session?.sessionId?{sessionId:session.sessionId}:await create('work',text.slice(0,28));await local('submit',{sessionId:t.sessionId,text});setPrompt('');await refresh();}
    catch(e){notify(e.message);}finally{setPendingSend(false);}
  }
  async function startSkill() {if(requireModel())return;const t=await create('skill','创建个人 Skill');setModal(null);const text=prompt.trim();setPrompt('');await local('submit',{sessionId:t.sessionId,text:`/plan 帮我创建 Skill。先询问用途、输入输出与必要选择，再用 tulip_skill_draft 提交 Markdown 草稿；等待我在工作台编辑和确认保存。${text?'我的需求：'+text:'请先询问我想创建什么 Skill。'}`});await refresh();}
  async function startReview() {if(!prompt.trim()){notify('先在输入框写下希望评审的问题');return;}if(requireModel())return;const text=prompt;const t=await create('review',`评审：${text.slice(0,24)}`);setPrompt('');await local('submit',{sessionId:t.sessionId,text});await refresh();}
  async function togglePlan() {
    if(requireModel())return;
    const t=session?.sessionId?{sessionId:session.sessionId}:await create('work','规划新任务');
    const target=!planMode;await harness.command(t.sessionId,target?'/plan':'/plan off');
    const h=await harness.history(t.sessionId,150);setThread(threadFromHistory(h.events));setProjections(h.projections?.values||{});await refresh();
    notify(target?'已进入规划：先得到你确认，再执行':'已切换为直接执行');
  }
  async function archiveTask(sessionId,archived) {
    await local('tasks/archive',{sessionId,archived});setTaskMenu(null);await refresh();
    notify(archived?'已归档，可在“已归档”中查看和恢复':'已恢复到最近任务');
  }
  function archivedSession(task) {
    const found=sessions.find(s=>s.sessionId===task.sessionId);if(found)return found;
    const project=state.projects.find(p=>p.id===task.projectId);
    return {sessionId:task.sessionId,title:task.title,cwd:project?.path};
  }
  async function addProject(rebindId) {const picked=await harness.pickDirectory();if(!picked?.path)return;if(rebindId)await local('projects/rebind',{id:rebindId,path:picked.path});else await harness.createWorkspace(picked.path);await refresh();}
  async function loadMemory(name=memoryName) {const m=await local(`memory?name=${encodeURIComponent(name)}`);setMemory(m);setMemoryName(name);setMemoryNames(await local('memory'));setPanel('memory');}
  async function answer(rpcId,value){await local('respond',{rpcId,value});await refresh();}
  function projectOpen(p){setProjectId(p.id);fresh();setPanel('project');}
  const renderMessage=(item,i)=>{
    if(item.kind==='user')return <div className="cx-user" key={i}><p>{userText(item.text)}</p></div>;
    if(item.kind==='tool')return <details className="tu-tool" key={i}><summary>{item.status==='error'?'出错':item.status==='done'?'完成':'工具'} · {item.tool} {item.title}</summary><pre>{item.detail}</pre></details>;
    if(item.kind==='approval')return null;
    return <div className="cx-agent" key={i}><span className="cx-agent-mark">✦</span><div className="cx-agent-body"><small>Tulip{item.model?` · ${item.model}`:''}</small><div className="tu-markdown"><Markdown remarkPlugins={[remarkGfm]}>{item.text}</Markdown></div></div></div>;
  };

  return <main className={`wb ${sidebar?'':'wb-focus'}`}>
    {sidebar&&<aside className="wb-sidebar"><div className="wb-brand"><img src="/assets/deepseek-fish.svg" alt=""/><strong>Tulip<span>个人工作台</span></strong><button aria-label="收起侧栏" onClick={()=>setSidebar(false)}><List size={18}/></button></div><button className="wb-new" onClick={fresh}><Plus size={17}/>新对话</button><button className="wb-search" onClick={()=>setModal('search')}><MagnifyingGlass size={16}/>搜索任务<kbd>⌘K</kbd></button><div className="wb-nav-scroll"><button className={`wb-nav-item ${view==='today'?'is-current':''}`} onClick={()=>setView('today')}><House size={17}/>今天</button><div className="wb-section-label">项目<button aria-label="添加项目" onClick={()=>act(()=>addProject())}><Plus size={15}/></button></div>{state.projects.map(p=><button className={`wb-nav-item ${projectId===p.id?'is-project':''}`} key={p.id} title={p.path||'需要绑定文件夹'} onClick={()=>projectOpen(p)}><FolderSimple size={16}/><span>{p.title}</span>{!p.path&&<small>待绑定</small>}</button>)}<div className="wb-section-label">最近任务</div>{recentSessions.slice(0,60).map(s=><SidebarTask key={s.sessionId} summary={s} task={state.tasks.find(t=>t.sessionId===s.sessionId)} state={state} sessions={sessions} current={session?.sessionId} onSelect={value=>act(()=>select(value))} taskMenu={taskMenu} setTaskMenu={setTaskMenu} onArchive={(id,value)=>act(()=>archiveTask(id,value))}/>)}<button className="wb-nav-item wb-archive-entry" onClick={()=>setModal('archived')}><Archive size={16}/><span>已归档</span>{archivedTasks.length>0&&<small>{archivedTasks.length}</small>}</button></div><div className="wb-sidebar-foot"><div><button onClick={()=>act(async()=>{const result=await local('skills'+(session?.sessionId?`?sessionId=${encodeURIComponent(session.sessionId)}`:''));setSkills(result.items);setModal('skills');})}><SquaresFour size={16}/>能力</button><button onClick={()=>setModal('settings')}><GearSix size={16}/>设置</button></div><button className="wb-connection" onClick={()=>modelReady===false&&setModal('modelSetup')}><i className={!connected?'connecting':modelReady===false?'missing':'connected'}/>{!connected?'服务重连中':modelReady===false?'模型未连接':'模型可用'}</button></div></aside>}
    <section className="wb-main"><header className="wb-header">{!sidebar&&<button aria-label="展开侧栏" onClick={()=>setSidebar(true)}><List size={18}/></button>}<div className="wb-title"><strong>{view==='today'?'今天':session?.title||task?.title||(session?titleFromSummary(session):'新对话')}</strong><span>{project?.title||'个人工作台'}</span></div><div className="wb-header-actions"><button title="项目与产出" aria-label="项目与产出" onClick={()=>setPanel(panel==='project'?null:'project')}><FolderSimple size={18}/></button><button title="本地记忆" aria-label="本地记忆" onClick={()=>act(()=>loadMemory())}><FileText size={18}/></button><button title="产出预览" aria-label="产出预览" onClick={()=>setPanel(panel==='preview'?null:'preview')}><Browser size={18}/></button><button title="日程安排" aria-label="日程安排" onClick={()=>setModal('schedule')}><CalendarBlank size={18}/></button></div></header>
    {error&&<div className="wb-error" role="alert">{error}<button onClick={()=>{setError('');act(refresh);}}>重试</button></div>}
    <div className={`wb-body ${panel?'with-panel':''}`}><div className="wb-conversation">
    {view==='today'?<div className="today-page"><header className="today-page-head"><div><span className="today-eyebrow">PERSONAL WORKBENCH</span><h1>今天，从这里继续</h1><p>{new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})} · {state.todos.filter(t=>!t.done).length} 件待办</p></div><button className="whale-float" aria-label="小鲸鱼" onClick={()=>notify('今天也一起把事情做好。')}><img src="/assets/deepseek-fish.svg" alt=""/></button></header><div className="today-grid">
    <section className="today-card"><header><h2>今天要做</h2></header><form className="tu-inline" onSubmit={e=>{e.preventDefault();act(async()=>{await local('work',{operation:'todo',args:{text:todoInput}});setTodoInput('');await refresh();});}}><input aria-label="新增待办" placeholder="记下一件事…" value={todoInput} onChange={e=>setTodoInput(e.target.value)}/><button disabled={!todoInput.trim()}><Plus size={16}/></button></form><div className="todo-list">{state.todos.map(t=><label key={t.id} className={t.done?'is-done':''}><input type="checkbox" checked={t.done} onChange={()=>act(async()=>{await local('work',{operation:'todo',args:{...t,done:!t.done}});await refresh();})}/><span>{t.text}</span></label>)}</div>{!state.todos.length&&<p className="wb-muted">还没有待办，也可以在对话里安排。</p>}</section>
    <section className="today-card project-card"><header><h2>项目近况</h2></header><div className="project-list">{state.projects.map(p=>{const r=state.runs.find(r=>r.projectId===p.id);return <button key={p.id} onClick={()=>projectOpen(p)}><FolderSimple size={17}/><span><strong>{p.title}</strong><small>{r?`${statusLabels[r.status]||r.status} · ${r.text?.slice(0,38)||''}`:'还没有执行记录'}</small></span><ArrowRight size={14}/></button>;})}</div>{!state.projects.length&&<button onClick={()=>act(()=>addProject())}>添加项目文件夹</button>}</section>
    <section className="today-card"><header><h2>安排与提醒</h2><button onClick={()=>setModal('schedule')}><Plus size={16}/></button></header>{state.schedules.map(s=><div className="tu-row" key={s.id}><span><strong>{s.title}</strong><small>{new Date(s.nextAt).toLocaleString()} · {s.timezone} · {s.enabled?'已启用':'已暂停 / 单次结束'}</small></span><button onClick={()=>act(async()=>{await local('schedule/toggle',{id:s.id,enabled:!s.enabled});await refresh();})}>{s.enabled?'暂停':'启用'}</button>{s.kind==='task'&&<button onClick={()=>act(async()=>{await local('schedule/run',{id:s.id});await refresh();})}>现在运行</button>}</div>)}{!state.schedules.length&&<p className="wb-muted">“明天下午提醒我验收”，也可以直接告诉 Tulip。</p>}<small className="wb-muted">仅在本地服务运行且电脑唤醒时触发。</small></section>
    <section className="today-card"><header><h2>需要关注</h2></header>{state.pending.map(f=><button className="tu-row" key={f.rpcId} onClick={()=>act(()=>select({sessionId:f.payload.sessionId}))}>有一项选择等待回答 <ArrowRight size={14}/></button>)}{state.notifications.filter(n=>!n.read).map(n=><div className="tu-row" key={n.id}><button onClick={()=>n.sessionId?act(()=>select({sessionId:n.sessionId})):notify(n.text)}><strong>{n.title}</strong><small>{n.text}</small></button><button aria-label="标记已读" onClick={()=>act(async()=>{await local('notification/read',{id:n.id});await refresh();})}><Check size={15}/></button></div>)}{!state.pending.length&&!state.notifications.some(n=>!n.read)&&<p className="wb-muted">暂时没有需要处理的事情。</p>}</section></div><button className="today-quick-start" onClick={fresh}><Sparkle size={16}/>开始一次对话<ArrowRight size={15}/></button></div>
    :<div className="codex-surface"><div className="codex-thread" ref={threadEl} onScroll={e=>{follow.current=e.currentTarget.scrollHeight-e.currentTarget.scrollTop-e.currentTarget.clientHeight<80;}}>{!thread.length&&<div className="codex-empty"><img className="wb-welcome-whale" src="/assets/deepseek-fish.svg" alt=""/><h1>{project?`一起推进 ${project.title}`:'今天想把什么做出来？'}</h1><p>可以先讨论，也可以直接交代任务。</p></div>}{thread.map(renderMessage)}
    {children.length>0&&<details className="tu-question"><summary>协作 Agent · {children.length}</summary>{children.map(child=><div className="tu-row" key={child.id}><span>{child.label||child.id}<small>{child.kind==='diagnostic'?child.reason:child.activity==='running'?'执行中':'已停止运行 · 查看结果'}</small></span><button onClick={()=>act(async()=>{const h=await harness.childHistory(session.sessionId,child);setChildText(threadFromHistory(h.events).filter(i=>i.kind==='agent').map(i=>i.text).join('\n\n')||'还没有输出');})}>结果</button>{child.mode==='continuable'&&child.activity==='running'&&<button onClick={()=>act(()=>harness.interruptChild(session.sessionId,child))}>停止</button>}</div>)}{childText&&<pre>{childText}</pre>}</details>}
    {pending.map(f=><Question key={f.rpcId} frame={f} onAnswer={answer}/>)}
    {state.drafts.filter(d=>d.sessionId===session?.sessionId&&d.status==='draft').map(d=><div className="tu-question" key={d.id}><strong>Skill 草稿：{d.name}</strong><p>{d.description}</p><button onClick={()=>{setSelectedDraft(d);setDraftContent(d.content);setModal('draft');}}>编辑与确认保存</button><button onClick={()=>act(async()=>{await local('drafts/cancel',{id:d.id});await refresh();})}>取消草稿</button></div>)}
    {discussion&&<section className="tu-discussion"><header><span><strong>方案工作稿</strong><small>{{brief:'准备中',innovation:'创新初稿完成','engineering-review':'工程评审完成','innovation-revision':'创新修订完成','engineering-delivery':'落地计划完成',final:discussion.status==='confirmed'?'已确认并交给执行会话':'等待确认'}[discussion.stage]}</small></span><em>{discussion.executionStatus==='needs-attention'?'执行需处理':discussion.executionStatus==='completed'?'执行完成':discussion.status==='confirmed'?'已进入执行':discussion.status==='pending-confirmation'?'待你确认':'协作中'}</em></header><div className="tu-discussion-steps">{[['innovation','创新 Agent'],['engineering-review','工程 Agent 评审'],['innovation-revision','创新 Agent 修订'],['engineering-delivery','工程 Agent 落地']].map(([key,label])=><span className={discussion.sections?.[key]?'done':''} key={key}><i>{discussion.sections?.[key]?'✓':'·'}</i>{label}</span>)}</div><details><summary>查看共享文档</summary><div className="tu-markdown"><Markdown remarkPlugins={[remarkGfm]}>{`# ${discussion.title}\n\n## 目标与约束\n${discussion.brief}\n\n## 创新方案\n${discussion.sections?.innovation||'等待创新 Agent'}\n\n## 工程评审\n${discussion.sections?.['engineering-review']||'等待工程 Agent'}\n\n## 修订方案\n${discussion.sections?.['innovation-revision']||'等待创新 Agent 修订'}\n\n## 落地计划\n${discussion.sections?.['engineering-delivery']||'等待工程 Agent 收尾'}\n\n## Tulip 汇总\n${discussion.sections?.final||'等待 Tulip 汇总'}`}</Markdown></div></details>{discussion.status==='pending-confirmation'&&<button onClick={()=>act(async()=>{const result=await local('discussions/confirm',{id:discussion.id});await refresh();notify(`方案已确认，已创建 ${result.tasks?.length||0} 个执行会话`);})}>确认方案并开始执行</button>}</section>}
    {run&&<div className={`tu-run ${run.status}`} role="status">{statusLabels[run.status]||run.status}{run.error&&<small>{run.error}</small>}{run.status==='completed'&&<small>请结合产出与验证结果验收。</small>}</div>}
    <ExecutionGroup task={task?.parentTaskId?state.tasks.find(parent=>parent.id===task.parentTaskId):task} state={state} sessions={sessions} onSelect={value=>act(()=>select(value))}/>
    </div><div className={`codex-composer ${planMode?'is-plan':''}`}><div className="cx-input-row"><textarea aria-label="给 Tulip Agent 下指令" placeholder={planMode?'描述目标，Tulip 会先整理方案，确认后再执行…':'说说你的想法，或交代一件事…'} value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send();}}}/><div className="cx-composer-tools"><button className={`cx-chip cx-plan-chip ${planMode?'active':''}`} disabled={!connected||pendingSend||running} onClick={()=>act(togglePlan)}><span/>{planMode?'先规划':'直接做'}</button><button className="cx-chip" disabled={!connected||pendingSend} onClick={()=>act(startSkill)}><Sparkle size={13}/>创建 Skill</button><button className="cx-chip" disabled={!connected||pendingSend} onClick={()=>act(startReview)}>多视角评审</button><select aria-label="模型" value={modelReady===false?'':model} onClick={()=>modelReady===false&&setModal('modelSetup')} onChange={e=>act(async()=>{if(!e.target.value){setModal('modelSetup');return;}const m=models.find(m=>m.key===e.target.value);await harness.selectModel(session.sessionId,{provider:m.provider,model:m.id,reasoningEffort:m.reasoning?.defaultEffort});setModel(m.key);})} disabled={modelReady!==false&&(!session||running)}>{modelReady===false?<option value="">连接模型</option>:models.length?models.map(m=><option key={m.key} value={m.key}>{m.name||m.id} · {m.provider}</option>):<option>{model.split('::').at(-1)||'连接模型'}</option>}</select><button className={`cx-send ${running?'cancel':''}`} aria-label={running?'停止':'发送'} disabled={!connected||pendingSend||(!running&&!prompt.trim())} onClick={()=>running?act(async()=>{await harness.cancel(session.sessionId);await refresh();}):send()}>{running?<X size={15}/>:<ArrowUp size={15}/>}</button></div></div><div className="cx-hint"><span>{modelReady===false?'连接模型后即可执行':planMode?'规划模式不会在确认前修改项目':'Enter 发送 · Shift + Enter 换行'}</span>{telemetry.total>0&&<details className="tu-token-meter"><summary>本会话 {tokenLabel(telemetry.total)} tokens{telemetry.percent!=null?` · 上下文 ${telemetry.percent}%`:''}</summary><div><strong>输入 {tokenLabel(telemetry.input)} · 输出 {tokenLabel(telemetry.output)}</strong>{telemetry.capacity&&<span>当前上下文约 {tokenLabel(telemetry.used)} / {tokenLabel(telemetry.capacity)}</span>}<span>组成估算：系统 {tokenLabel(telemetry.breakdown.system)} · 工具 {tokenLabel(telemetry.breakdown.tools)} · 对话 {tokenLabel(telemetry.breakdown.messages)}</span></div></details>}</div></div></div>}
    </div>
    {panel==='preview'&&<PreviewPanel state={state} task={task} projectId={projectId} selectedId={selectedPreview} onSelect={setSelectedPreview} onClose={()=>setPanel(null)} onRefresh={refresh} width={previewWidth} onResize={setPreviewWidth} notify={notify}/>} 
    {panel&&panel!=='preview'&&<aside className="wb-panel tu-panel"><header><strong>{{project:'项目与产出',memory:'本地记忆'}[panel]}</strong><button aria-label="关闭面板" onClick={()=>setPanel(null)}><X size={17}/></button></header>
    {panel==='memory'&&<div className="tu-panel-body"><select aria-label="记忆文件" value={memoryName} onChange={e=>act(()=>loadMemory(e.target.value))}>{[...new Set(['MEMORY.md',...memoryNames,...(projectId?['overview','decisions','progress'].map(n=>`projects/${projectId}/${n}.md`):[])])].map(n=><option key={n}>{n}</option>)}</select><small>本地 Markdown。当前项目之外的记忆不会自动带入。外部修改冲突时需重新加载。</small><textarea aria-label="记忆内容" value={memory?.content||''} onChange={e=>setMemory(m=>({...m,content:e.target.value}))}/><div className="tu-inline"><button disabled={!memory} onClick={()=>act(async()=>{const m=await local('memory',memory);setMemory(m);notify('记忆已保存，下次请求使用新内容');})}>保存记忆</button><button onClick={()=>act(()=>loadMemory())}>重新加载</button></div></div>}
    {panel==='project'&&<div className="tu-panel-body"><h3>{project?.title||'个人工作台'}</h3><small>{project?.path||'未绑定项目目录'}</small>{project&&!project.path&&<button onClick={()=>act(()=>addProject(project.id))}>绑定当前电脑的文件夹</button>}<button onClick={()=>act(()=>loadMemory(projectId?`projects/${projectId}/progress.md`:'MEMORY.md'))}>查看工作记忆</button><h3>项目方案</h3>{state.plans.filter(p=>p.projectId===projectId).map(p=><details key={p.id}><summary>v{p.version} · {p.title} · {({proposed:'建议',decided:'已决定',hypothesis:'假设',discarded:'已放弃'})[p.status]}</summary><pre>{p.content}</pre><button onClick={()=>act(async()=>{const t=await create('work',`执行：${p.title}`);await local('submit',{sessionId:t.sessionId,text:'按照我选择的方案执行，先检查项目现状，完成后验证。',planId:p.id});await refresh();})}>按此版本执行</button><button onClick={()=>{setPlanText(p.content);setPlanStatus('proposed');}}>修订为新版本</button></details>)}{projectId&&<><textarea aria-label="方案内容" placeholder="记录建议、决定或待验证假设…" value={planText} onChange={e=>setPlanText(e.target.value)}/><select aria-label="方案状态" value={planStatus} onChange={e=>setPlanStatus(e.target.value)}><option value="proposed">建议</option><option value="decided">已决定</option><option value="hypothesis">假设</option><option value="discarded">已放弃</option></select><button disabled={!planText.trim()} onClick={()=>act(async()=>{await local('work',{operation:'plan',args:{projectId,title:'项目方案',content:planText,status:planStatus}});setPlanText('');await refresh();})}>保存方案版本</button></>}<h3>产出</h3>{state.artifacts.filter(a=>a.projectId===projectId).map(a=>{const preview=state.previews.find(p=>p.artifactId===a.id);return <button key={a.id} onClick={()=>act(async()=>{if(preview){setSelectedPreview(preview.id);setPanel('preview');}else{setArtifact(await local(`artifact?id=${a.id}`));setModal('artifact');}})}>{a.title} {preview?'· 预览':'↗'}</button>;})}<small>HTML 和 Markdown 产出会自动打开；Mermaid 代码块可直接渲染和编辑。</small></div>}
    </aside>}</div></section>
    {modal==='search'&&<Modal title="搜索任务" onClose={()=>setModal(null)}><input autoFocus aria-label="搜索任务" value={search} onChange={e=>setSearch(e.target.value)}/>{sessions.filter(s=>titleFromSummary(s).toLowerCase().includes(search.toLowerCase())).map(s=><button className="tu-row" key={s.sessionId} onClick={()=>act(()=>select(s))}>{titleFromSummary(s)}</button>)}</Modal>}
    {modal==='archived'&&<Modal title="已归档" className="tu-archive-dialog" onClose={()=>setModal(null)}><p className="tu-archive-intro">归档只会从最近任务中收起，不会删除对话、产出或项目关联。</p><div className="tu-archive-list">{archivedTasks.map(t=>{const p=state.projects.find(p=>p.id===t.projectId);return <div className="tu-archive-row" key={t.id}><span><strong>{t.title||titleFromSummary(archivedSession(t))}</strong><small>{p?.title||'个人工作台'} · {new Date(t.archivedAt).toLocaleDateString('zh-CN')}</small></span><button onClick={()=>act(()=>select(archivedSession(t)))}>查看</button><button onClick={()=>act(()=>archiveTask(t.sessionId,false))}><ArrowCounterClockwise size={14}/>恢复</button></div>;})}{!archivedTasks.length&&<div className="tu-archive-empty"><Archive size={26}/><p>还没有归档任务</p></div>}</div></Modal>}
    {modal==='skills'&&<Modal title="我的能力" onClose={()=>setModal(null)}><p>Skill 定义工作方法；执行能力由实际连接的工具提供。</p>{[['product','产品'],['development','开发']].map(([id,label])=><section key={id}><h3>{label}</h3>{skills.filter(s=>s.category===id).map(s=><details key={s.name}><summary>{s.name} · {s.status==='loadable'?'当前会话可加载':'文件已保存'}</summary><p>{s.description}</p>{s.name==='tulip-computer'&&<small>电脑操控工具尚未接通，不能仅凭 Skill 操作屏幕。</small>}<button onClick={()=>{setPrompt(p=>`/${s.name} ${p}`);setView('task');setModal(null);}}>放入对话</button><pre>{s.content}</pre></details>)}{!skills.some(s=>s.category===id)&&<small>还没有此类 Skill</small>}</section>)}<button className="wb-plugin-create" disabled={!connected} onClick={()=>act(startSkill)}>创建 Skill</button></Modal>}
    {modal==='draft'&&selectedDraft&&<Modal title="确认 Skill 草稿" onClose={()=>setModal(null)}><p>在这里编辑内容。点击确认才安装到本地 Skills。</p><textarea className="tu-draft-editor" aria-label="Skill 草稿内容" value={draftContent} onChange={e=>setDraftContent(e.target.value)}/><button onClick={()=>act(async()=>{await local('drafts/confirm',{id:selectedDraft.id,revision:selectedDraft.revision,content:draftContent});await refresh();setModal(null);notify('Skill 已保存；在普通工作会话中检查加载');})}>确认保存</button></Modal>}
    {modal==='schedule'&&<Modal title="新增安排" onClose={()=>setModal(null)}><form className="tu-form" onSubmit={e=>{e.preventDefault();act(async()=>{await local('work',{operation:'schedule',args:{...schedule,projectId,nextAt:new Date(schedule.at).toISOString(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone}});await refresh();setModal(null);notify('安排已保存');});}}><label>标题<input required value={schedule.title} onChange={e=>setSchedule(s=>({...s,title:e.target.value}))}/></label><label>类型<select value={schedule.kind} onChange={e=>setSchedule(s=>({...s,kind:e.target.value}))}><option value="reminder">提醒我</option><option value="task">到点执行任务</option></select></label><label>时间<input type="datetime-local" required value={schedule.at} onChange={e=>setSchedule(s=>({...s,at:e.target.value}))}/></label><label>重复<select value={schedule.recurrence} onChange={e=>setSchedule(s=>({...s,recurrence:e.target.value}))}><option value="once">仅一次</option><option value="daily">每天</option><option value="weekly">每周</option></select></label>{schedule.kind==='task'&&<label>任务内容<textarea required value={schedule.prompt} onChange={e=>setSchedule(s=>({...s,prompt:e.target.value}))}/></label>}<small>时区：{Intl.DateTimeFormat().resolvedOptions().timeZone}。本地服务运行时触发，休眠错过的执行不会自动补跑。</small><button>保存安排</button></form></Modal>}
    {modal==='settings'&&<Modal title="设置" className="tu-settings-dialog" onClose={()=>setModal(null)}><SettingsPanel model={model||host?.model} state={state} onModels={()=>setModal('models')} onMemory={()=>act(async()=>{await loadMemory('MEMORY.md');setModal(null);})} onImport={async(data)=>{const result=await local('import',data);await refresh();return result;}}/></Modal>}
    {modal==='models'&&<Modal title="模型与 API" className="tu-model-dialog" onClose={()=>setModal(null)}><ModelSettings onReady={setModelReady} onChanged={()=>refresh().catch(()=>{})}/></Modal>}
    {modal==='modelSetup'&&<Modal title="首次连接" className="tu-model-dialog" onClose={()=>setModal(null)}><ModelSettings firstRun onReady={ready=>{setModelReady(ready);if(ready)setModal(null);}} onChanged={()=>refresh().catch(()=>{})}/></Modal>}
    {modal==='artifact'&&artifact&&<Modal title={artifact.title} onClose={()=>setModal(null)}><small>{artifact.path}</small><pre>{artifact.content}</pre></Modal>}
    {toast&&<div className="wb-toast" role="status">{toast}</div>}
  </main>;
}
